version: 2
updates:
  # Rust dependencies in the PQC library
  - package-ecosystem: "cargo"
    directory: "/src/portal/mock-qynauth/src/rust_lib"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ronakminkalla"
    labels:
      - "dependencies"
      - "pqc"
      - "security"
    commit-message:
      prefix: "deps"
      include: "scope"
    
    # Group PQC-related updates
    groups:
      pqc-core:
        patterns:
          - "pqcrypto-*"
        
      security-libs:
        patterns:
          - "zeroize"
          - "subtle" 
          - "secrecy"
          
      crypto-utils:
        patterns:
          - "rand"
          - "getrandom"
          
    # Ignore major version updates for stability
    ignore:
      - dependency-name: "pqcrypto-*"
        update-types: ["version-update:semver-major"]

  # Node.js dependencies in the main application
  - package-ecosystem: "npm"
    directory: "/src/portal/portal-backend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "ronakminkalla"
    labels:
      - "dependencies"
      - "backend"
