[build]
# Remove hardcoded target for cross-platform compatibility

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "target-cpu=native",
  "-C", "target-feature=+aes,+sse2,+sse4.1,+popcnt"
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
  "-C", "target-cpu=native"
]

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "target-cpu=native",
  "-C", "target-feature=+aes,+sse2,+sse4.1,+popcnt"
]

[alias]
build-pqc = "build --features kyber768,dilithium3,avx2"
build-all = "build --all-features"
bench-pqc = "bench --features kyber768,dilithium3,avx2"
check-security = "deny check"
audit-deps = "audit"
