services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # CRITICAL: Use env_file to load ALL environment variables from .env
    env_file:
      - .env
    # Only put truly fixed or dev-specific overrides here.
    # We also explicitly pass AWS credentials from host here.
    environment:
      - NODE_ENV=development # Explicitly set for dev environment
      - ENABLE_SWAGGER_DOCS=true # Explicitly set for dev environment
      - PORT=8080 # Explicitly set for dev environment
      # ADDED: Pass AWS credentials from your host environment
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN} # Uncomment if you use temporary session tokens

    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ping: 1})"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  mongo-data: