# Dependency monitoring and security configuration for PQC implementation
[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
]

[licenses]
# Use version 2 configuration format
version = 2

# Only allow compatible licenses
allow = [
    "MIT",
    "Apache-2.0", 
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unicode-3.0",
]

# With version = 2, licenses not in allow list are automatically denied

[bans]
# Deny multiple versions of the same crate
multiple-versions = "deny"

# Deny specific problematic crates
deny = [
    # Add any problematic crates here if needed
]

# Skip certain crates from multiple version checking if needed
skip = [
    # Add exceptions if needed
]

skip-tree = [
    # Skip entire dependency trees if needed
]

[advisories]
# Use version 2 configuration format
version = 2

# Deny yanked crates
yanked = "deny"

# Ignore specific advisories if needed
ignore = [
    # Ignore unmaintained paste crate (transitive dependency, low risk)
    "RUSTSEC-2024-0436",
]
