# Dependency monitoring and security configuration for PQC implementation
[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
]

[licenses]
# Only allow compatible licenses
allow = [
    "MIT",
    "Apache-2.0", 
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]

# Deny GPL and other copyleft licenses
deny = [
    "GPL-2.0",
    "GPL-3.0", 
    "AGPL-1.0",
    "AGPL-3.0",
]

# Require license information
unlicensed = "deny"
copyleft = "deny"

[bans]
# Deny multiple versions of the same crate
multiple-versions = "deny"

# Deny specific problematic crates
deny = [
    # Add any problematic crates here if needed
]

# Skip certain crates from multiple version checking if needed
skip = [
    # Add exceptions if needed
]

skip-tree = [
    # Skip entire dependency trees if needed
]

[advisories]
# Deny crates with security vulnerabilities
vulnerability = "deny"

# Allow unmaintained transitive dependencies, fail on workspace dependencies
unmaintained = "workspace"

# Deny crates with unsound code
unsound = "deny"

# Deny yanked crates
yanked = "deny"

# Ignore specific advisories if needed
ignore = [
    # Add specific advisory IDs to ignore
]
