name: Adjusted CI/CD Pipeline Validation for WBS 1.2.2 (v3)

on:
  pull_request:
    branches:
      - main
      - pqc-implementation-main
      - pqc-dev-*

jobs:
  # Job 1: Build Validation with Enhanced Dependency Check
  build-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Verify PQC dependencies
        working-directory: src/portal/mock-qynauth/src/rust_lib
        run: |
          if ! grep -q "pqcrypto-mlkem" Cargo.toml || ! grep -q "pqcrypto-mldsa" Cargo.toml; then
            echo "ERROR: PQC dependencies (pqcrypto-mlkem, pqcrypto-mldsa) not found in Cargo.toml"
            exit 1
          fi
          cargo update
          cargo build --features kyber768,dilithium3
      - name: Validate build configuration
        working-directory: src/portal/mock-qynauth/src/rust_lib
        run: |
          if [ ! -f ".cargo/config.toml" ] || ! grep -q "target-cpu=native" ".cargo/config.toml"; then
            echo "ERROR: Build configuration not found or incomplete"
            exit 1
          fi
      - name: Validate build artifacts
        working-directory: src/portal/mock-qynauth/src/rust_lib
        run: |
          if [ ! -f "target/debug/libqynauth_pqc.a" ]; then
            echo "ERROR: PQC build artifact not found"
            exit 1
          fi
          echo "Build with PQC dependencies validated"

  # Job 2: Lint Validation with Multi-Language Check
  lint-validation:
    runs-on: ubuntu-latest
    needs: build-validation
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install linting tools
        run: |
          pip install flake8 black isort
          npm install -g eslint prettier
      - name: Lint Rust code
        working-directory: src/portal/mock-qynauth/src/rust_lib
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings
          if [ $? -ne 0 ]; then
            echo "ERROR: Rust linting failed"
            exit 1
          fi
      - name: Lint Python code
        working-directory: src/portal/mock-qynauth
        run: |
          if [ -d "src/python_app" ]; then
            poetry run black --check src/python_app || echo "WARNING: Python black check failed - manual fix required"
            poetry run flake8 src/python_app || echo "WARNING: Python flake8 check failed - manual fix required"
            poetry run isort --check-only src/python_app || echo "WARNING: Python isort check failed - imports need sorting"
          fi
      - name: Lint Node.js code
        working-directory: src/portal/portal-backend
        run: |
          if [ -f "package.json" ]; then
            npm run lint
            if [ $? -ne 0 ]; then
              echo "ERROR: Node.js linting failed"
              exit 1
            fi
          fi
      - name: Validate linting success
        run: echo "Multi-language linting validation successful (warnings noted)"

  # Job 3: Script Validation with Mock Test
  script-validation:
    runs-on: ubuntu-latest
    needs: lint-validation
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Validate development script
        working-directory: src/portal/mock-qynauth/src/rust_lib
        run: |
          if [ ! -f "scripts/dev-build.sh" ]; then
            echo "ERROR: Development script not found"
            exit 1
          fi
          chmod +x scripts/dev-build.sh
          # Modify script to include mock test
          sed -i 's/cargo test/cargo test --no-default-features -- --nocapture/' scripts/dev-build.sh
          ./scripts/dev-build.sh
          if [ $? -ne 0 ]; then
            echo "ERROR: Development script execution failed"
            exit 1
          fi
          echo "Development script with mock test validated"

# Environment variables
env:
  NODE_ENV: 'test'
