name: CI Pipeline – Frontend and Backend

on:
  pull_request:
    paths:
      - 'src/portal/portal-frontend/**'
      - 'src/portal/portal-backend/**'
      - 'docs/**'
      - '.github/workflows/ci.yml'

jobs:
  backend:
    name: 🔧 Backend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/portal/portal-backend
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npm run typecheck

      - name: Tests
        run: npm test
        env:
          MONGO_URI: ${{ secrets.MONGODB1 }}
          NODE_ENV: test

      - name: Doc Validation
        run: |
          test -s docs/paperwork.md || (echo 'Missing paperwork.md' && exit 1)
          test -s docs/PR_SECURITY_CHECKLIST.md || (echo 'Missing PR_SECURITY_CHECKLIST.md' && exit 1)

  frontend:
    name: 🎨 Frontend CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/portal/portal-frontend
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npm run typecheck

      - name: Tests
        run: npm test
        env:
          MONGO_URI: ${{ secrets.MONGODB1 }}
          NODE_ENV: test

      - name: Doc Validation (optional for frontend)
        run: |
          echo "Skipping documentation checks for frontend."
# MongoDB Atlas validation trigger
