name: PQC Basic Build Check

on:
  pull_request:
    branches:
      - main
      - pqc-implementation-main
      - pqc-dev-*

jobs:
  pqc-basic-build:
    name: "🦀 PQC Basic Build Check"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Basic build check
        working-directory: src/portal/mock-qynauth/src/rust_lib
        run: |
          cargo check
          cargo fmt --check
          cargo clippy -- -D warnings
      - name: Run basic tests
        working-directory: src/portal/mock-qynauth/src/rust_lib
        run: |
          cargo test --release

# Environment variables
env:
  NODE_ENV: 'test'
  AWS_REGION: 'us-east-1'
