name: Adjusted CI/CD Pipeline Validation for WBS 1.2.2

on:
  pull_request:
    branches:
      - pqc-implementation-main
      - pqc-dev-*

jobs:
  # Job 1: Build Validation with PQC Dependencies
  build-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install PQC dependencies
        working-directory: src/portal/mock-qynauth/src/rust_lib
        run: |
          cargo update
          cargo build --features kyber768,dilithium3
      - name: Validate build artifacts
        working-directory: src/portal/mock-qynauth/src/rust_lib
        run: |
          if [ ! -f "target/debug/libqynauth_pqc.a" ]; then
            echo "ERROR: PQC build artifact not found"
            exit 1
          fi
          echo "Build with PQC dependencies validated"

  # Job 2: Lint Validation
  lint-validation:
    runs-on: ubuntu-latest
    needs: build-validation
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Install linting tools
        run: |
          pip install flake8 black isort
      - name: Lint Rust code
        working-directory: src/portal/mock-qynauth/src/rust_lib
        run: |
          cargo fmt --all -- --check
          cargo clippy -- -D warnings
          if [ $? -ne 0 ]; then
            echo "ERROR: Rust linting failed"
            exit 1
          fi
      - name: Validate linting success
        run: echo "Linting validation successful"

  # Job 3: Script Validation
  script-validation:
    runs-on: ubuntu-latest
    needs: lint-validation
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Validate development script
        working-directory: src/portal/mock-qynauth/src/rust_lib
        run: |
          if [ ! -f "scripts/dev-build.sh" ]; then
            echo "ERROR: Development script not found"
            exit 1
          fi
          chmod +x scripts/dev-build.sh
          ./scripts/dev-build.sh
          if [ $? -ne 0 ]; then
            echo "ERROR: Development script execution failed"
            exit 1
          fi
          echo "Development script validated"

# Environment variables
env:
  NODE_ENV: 'test'
